name: CI/CD

on:
  push:
    branch: ['main']
  pull_request:

jobs:

  check:
    name: continuous integration checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: cargo cache
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ hashFiles('Cargo.lock') }}-dev

      - name: npm cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('pnpm-lock.yaml') }}
      - name: make check
        run: make check

  push_container:
    name: build and push Docker container
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: Kubernetes
    steps:
      - uses: act